remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

title: How to predict ratings of new Airbnb's? ğŸ 
description: Insights about Australian Airbnb accommodations.

show_downloads: false
